version: "3.9"

services:
  db_prod:
    image: postgres:16
    env_file:
      - ./stack.env
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - demain-net

  db_dev:
    image: postgres:16
    env_file:
      - ./stack.env
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - demain-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./stack.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db_prod
      - db_dev
    networks:
      - demain-net

volumes:
  pgdata_prod:
  pgdata_dev:

networks:
  demain-net:
    driver: bridge